### ISSUE TITLE
open question - automate without id, className or name

### ISSUE THREAD

**Issue by thot636** [2gis/Winium.Desktop#111]
Hey,

Question to 2gis guys. Have you ever wonder to implement in WInium functionality  to find elements (when you cannot recognize them by any means like id, className) ? - maybe similar how Sikuli works. The reason for this question is that we need to implement automation for Desktop Windows app which has a lot of components which cannot be recognized by id, automatedID, name, className or any other fields.

Thanks,
Krzysiek

**Comment by NickAb** [comment]
What do you mean by functionality similar to how Sikuli works? Are you talking about image recognition? I don't think we thought about implementing it and it might result in very slow test runs.

You can try using XPath locators to test the app that does not have distinctive enough ids or class names. XPath will let you to build queries to get to the element you want, you would be able to use different properties of elements, that are seen by UISpy to locate elements. 
It is recommended to write XPath in such a way as to try to reduce search scope on each level. For example `/*[@AutomationId='MyMainWindow']//*[@Name='Add Event']` will be preferable over `//*[@Name='Завершена']` as the former has much more limited scope on the top level, than the latter.

But if you have access to the app development process, then investing in testability might be beneficial.

**Comment by thot636** [comment]
Thanks for your quick answer. I was thinking about Xpath but in this app we have to test has  very deep elements's hierarchy ( 10 and more  sometimes) and it is not advisable to use. Moreover there are  dataGrids and it is impossible to distinguish some cells (they have exactly the same properties' names, when checking via UIspy or inspect). 

The thing is , it is external app and we cannot be involved in the development process in a way of its testability,,  

Regarding Sikuli, yes I was thinking about image recognition.

Thanks again,
Krzysiek

**Comment by NickAb** [comment]
I think you can use indexes and text properties in XPath. So in case of data grid you can access cell by index. If you know text value that should be displayed in the cell, then you can use it to locate the cell.

@skyline-gleb should be able to tell more about XPath.

**Comment by skyline-gleb** [comment]
@thot636 may I help you now?

**Comment by thot636** [comment]
@skyline-gleb, I dont need help, currently we have postponed to use Winium, we're doing currently just API testing without touching UI
 IF you want you can close issue as Obsolete / won't fix

Cheers,
Krzysiek

**Comment by skyline-gleb** [comment]
Okay. Good luck!

**Comment by sandeepkumar242007** [comment]
Hi All,
I am trying to identify the element like below, Some time it's working some it's not can someone let me know why its soo??

WebElement UserName = driver.findElementByXPath("//*[contains(@ControlType,'Edit') and contains(@Name,'User name:')]");
UserName.clear();
UserName.sendKeys("xyz");

![UserName](https://user-images.githubusercontent.com/42542293/56198732-20ca5e80-6059-11e9-96ed-594716997724.png)

And i am not getting any error message, I am not able to use ID because it's dynamic
@skyline-gleb 

Thanks in advance
Sandeep

**Comment by parthiih007** [comment]
Hey Guys,

Question to 2gis guys. Have you ever wonder to implement in WInium functionality to find elements (when you cannot recognize them by any means like id, className) ? Because I need to automatate for Desktop Windows app which has a lot of components which cannot be recognized by id, automatedID, name, className or any other fields.

Also I work on the Appium and find the Xpath but I didn't know how to use xpath in Winium. Also try to with  ClassName but In my application all edit field class name same. 

Thanks,
Parth Patel.
