### ISSUE TITLE
Interesting!! few WinForm elements are only visible 

### ISSUE THREAD

**Issue by SharonJacob** [2gis/Winium.Desktop#157]
I'm using UISpy to locate elements in my application. Only the first item under the tree is accessible. The remaining elements are NOT visible at all. Any idea why this happens? How to resolve it?

![image](https://cloud.githubusercontent.com/assets/22199830/24263051/619296d2-0fd2-11e7-8517-ba19aced9e0d.png)

**Comment by Sourabh25** [comment]
Are those objects under this pane windows object? Could you please confirm?

**Comment by SharonJacob** [comment]
@Sourabh25  Yes they are, I am able to view them by Inspect and not by UI Spy and code

**Comment by Sourabh25** [comment]
So with inspect element if you want to find the elements you should be able to write the automation script. Am i correct?

**Comment by SharonJacob** [comment]
@Sourabh25  I figured it out, I'm used unmanaged UIA for automation, It works better than managed UIAn:)

**Comment by Sourabh25** [comment]
where you can do that?

**Comment by SharonJacob** [comment]
@Sourabh25  It's simple, Instead of using UI Automation client 4.0, reference UI automation client from COM. You will need to change the synatax though

**Comment by Sourabh25** [comment]
Could you please explain me in detail. Actually I have similar scenario. I know the objects I need to identify are Rouge Wave Stingray grid control objects. I am not able to do it by UISpy or Inspector.

**Comment by SharonJacob** [comment]
If the application itself is not exposing elements. I'm not sure if you can think of automating them. You can always use images and try automating with Sikuli, but that's not reliable

**Comment by kiransirigireddy** [comment]
Hi Sharon,

We have similar issue where the Child Window is shown in Inspector but not in UISPY.
Can you please let me know the solution which you mentioned above with sample code.

**Comment by SharonJacob** [comment]
Hi, which language are you using?

**Comment by kiransirigireddy** [comment]
Java

**Comment by SharonJacob** [comment]
I use C# for desktop automation, There is UI automation client dll(2.0) that I use.
If you are interested to change to c#, I can help you with the syntax

**Comment by kiransirigireddy** [comment]
Yes i can shift to C# since still we are doing POC only

**Comment by SharonJacob** [comment]
Here's the sample code

 IUIAutomation _automation;
 _automation = new CUIAutomation();
//Get root element (desktop)
 IUIAutomationElement ele = _automation.GetRootElement();
//Find application window
var winLogin = ele.FindFirst(TreeScope.TreeScope_Children, _automation.CreatePropertyCondition(IDcondition, "Login"));
//Set focus on the application window
winLogin.SetFocus();

It's a little similar to Winium, let me know if you need more explanation

**Comment by Sourabh25** [comment]
@kiransirigireddy Could you please clarify what is the exact issue you are having? you should be restricted to any language due to objects. if you can do it in c#, you should be able to do it in java.

**Comment by kiransirigireddy** [comment]
Thanks a lot @SharonJacob for the help.

@Sourabh25 , I have pop up windows in my desktop application that are not shown in UISPY tree view but i can see them from Inspect. When i try with Winium + Java also i am not able to locate those pop up windows by using FindElements.

We can do this easily with C# either using Windows UI Automation API or White Framework where we have automated many Install Shields to drive deployments.

Why i am very specific or keen to drive this using Winium - Java because we have lot of automation scripts developed for Web Application using Selenium - Java and we need to call them to drive Workflows.

Basically I have workflows which run across 3 desktop applications and 4 Web Applications to complete.
Presently we use Test Complete to drive this where it provides a wrapper to call Selenium scripts inside Test Complete.

So wanted to replace Test Complete with Winium so that we get cost benefit and also another reason is slowly our Desktop applications are getting migrated to Web Applications where if i develop scripts in Winium i can use the same scripts developed on Desktop Application to drive on Web Application just by changing the Driver if my objects attribute values are maintained same.

If this can not be achieved by Winium + Java then i can plan with Winium + C# but need to see how i can call my Selenium +Java scripts from there.

Hope it is clear and any solutions for the above problem is appreciated.

**Comment by SharonJacob** [comment]
@kiransirigireddy  You may want to look at FlaUI, so far this is the best framework I came across for desktop automation.

https://github.com/Roemer/FlaUI

**Comment by Sourabh25** [comment]
@kiransirigireddy your problem statement really sounds interesting and challenging.. good learning curve...

**Comment by kiransirigireddy** [comment]
Thanks @SharonJacob

**Comment by autoasi** [comment]
Hi @SharonJacob,
I'm facing a similar issue as you - my objects are under pane object and I can view them with Inspect but not with UI Sky.
Could you please advise where can I find the UI automation client dll(2.0) you mentioned in your previous comments? 
I'm using VS 2015 on Windows 10 and can see only UIAutomationClient v1.0 under COM:
![image](https://user-images.githubusercontent.com/40855022/44470635-e8da5b00-a632-11e8-8635-621e23b4f112.png)
