### ISSUE TITLE
More detailed explanation

### ISSUE THREAD

**Issue by slovene1** [2gis/Winium.Desktop#20]
I am aware that Selenium does not work with WinForms by itself.  

Would it be possible to get a more detailed explanation of how Winium works with Selenium to be able to test a WinForms app?

Thanks!

**Comment by skyline-gleb** [comment]
Hi! You right.
But Winium.Desktop used Winium.Cruciatus for work with application (WinForms, WPF).
On 42 slide from [Winium](http://www.slideshare.net/codefest/winium?ref=http://2015.codefest.ru/lecture/1024) (conference CodeFest 2015) illustrated work scheme the whole chain.
How work with Winium.Desktop you make see in [Wiki](https://github.com/2gis/Winium.Desktop/wiki).
For research you tested application (get automationId, name, class name..) use [UISpy](https://github.com/2gis/Winium.Cruciatus/tree/master/tools/UISpy) or VisualUIAVerifyNative or inspect from Windows Kits.

**Comment by NickAb** [comment]
Hello.

To clarify what @skyline-gleb answered:

Winium.Desktop implements [JSONWireProtocol](https://code.google.com/p/selenium/wiki/JsonWireProtocol) adopted by Selenium.

ChromeDriver, FirefoxDriver, Appium and other test tools that are selenium-compatible, implement this protocol, so that end user could use selenium-bindings to write tests against any browser or mobile platform.

**So how does it work?**
Essentially Winium.Desktop is a REST server that implements JSONWWireProtocol and delegates implementation of automation commands to [Winium.Cruciatus](https://github.com/2gis/Winium.Cruciatus).

Winium.Cruciatus is C# library that provides automation related implementations, wraps UI Automation, input simulation and other libraries needed to automate desktop applications.

You could find more on how it all works and what it does support in [CodeFest talk](http://www.slideshare.net/codefest/winium) [in Russian] or in projects [wiki](https://github.com/2gis/Winium.Desktop/wiki).

To find out what elements driver will be able to locate and interact with, to determine locators that you could use to find such elements (automation id and name, class name, etc.) you could use [UISpy](https://github.com/2gis/Winium.Cruciatus/tree/master/tools/UISpy), VisualUIAVerifyNative or Inspect.exe from Windows Kits.

**Comment by NickAb** [comment]
@slovene1 have we answered your question or do you have anymore questions?
